### ISSUE TITLE
Question: ok soo time release? 😀

### ISSUE THREAD

**Issue by mcplayer50** [zacksgamerz/Funkin-Mic-d-Up-SC-Port4Android#4]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by mcplayer50** [comment]
why github comments so confusing 😀

**Comment by mcplayer50** [comment]
😫

**Comment by zacksgamerz** [comment]
![20210515_205650.jpg](https://user-images.githubusercontent.com/81515012/118387315-0ef88280-b648-11eb-8a9d-dea501f2664a.jpg)
No.
